// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Product struct {
	ID      string    `json:"id"`
	Name    string    `json:"name"`
	Reviews []*Review `json:"reviews,omitempty"`
}

type Query struct {
}

type Review struct {
	ID        string `json:"id"`
	Content   string `json:"content"`
	Rating    int    `json:"rating"`
	ProductID string `json:"productId"`
}
